# Generated by Django 5.2.4 on 2025-08-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ecommerce', '0001_initial'), ('ecommerce', '0002_productmodel_description'), ('ecommerce', '0003_productmodel_shortdescription'), ('ecommerce', '0004_remove_productmodel_shortdescription')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.FloatField()),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
