# Generated by Django 5.2.4 on 2025-08-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_squashed_0004_add_and_delete_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='availability',
            field=models.IntegerField(null=True),
        ),
    ]
