# Generated by Django 5.2.4 on 2025-08-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_productmodel_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='availability',
        ),
    ]
