# Generated by Django 5.2.4 on 2025-08-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_remove_productmodel_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('BR', 'BORRADOR'), ('PU', 'PUBLICADO'), ('PR', 'PRIVADO')], default='BR', max_length=2),
        ),
    ]
