# Generated by Django 5.2.4 on 2025-08-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_productmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('PU', 'Published'), ('DR', 'Draft'), ('PR', 'Private')], default='DR', max_length=2),
        ),
    ]
